### ISSUE TITLE
installされてないツールだけ入れるようにする

### ISSUE THREAD

**Issue by k-nasa** [k-nasa/dotfile#7]
install.shにおいて、よく使うツールを全部`brew install`で入れているけど、ありなしを判定して走らないようにしたい。

**Comment by ry-itto** [comment]
オススメ
https://github.com/ry-itto/dotfiles/blob/master/bootstrap.sh#L15-L21

**Comment by k-nasa** [comment]
@ry-itto ありがたい！使ってみる

**Comment by k-nasa** [comment]
Done
